---

- name: Proxmox Host Setup
  hosts: proxmox_hosts

  vars_files:
    - vars/proxmox_vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Install Proxmox Host dependencies
      ansible.builtin.apt:
        name:
          - libguestfs-tools
          - btop
          - tcpdump
        state: present
      tags:
        - proxmox_host_setup

