---

- name: Proxmox Host Setup
  hosts: brix

  vars_files:
    - vars/proxmox_vars.yml

  vars:
    container_templates:
      - ubuntu-24.04-standard_24.04-2_amd64.tar.zst
      - debian-12-standard_12.7-1_amd64.tar.zst
      - debian-13-standard_13.1-1_amd64.tar.zst
  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Install Proxmox Host Ansible dependencies
      ansible.builtin.apt:
        name:
          - python3-proxmoxer
          - python3-requests
          - python3-paramiko
        state: present
      tags:
        - proxmox_host_setup

    - name: Download Container Templates
      community.general.proxmox_template:
        api_host: brix.pcola.moorenix.com
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ brix_api_token_secret }}"
        node: brix
        storage: local
        template: "{{ item }}"
      loop: "{{ container_templates }}"
      tags:
        - container_templates
        - proxmox_host_setup



