---

- name: Proxmox Host Setup
  hosts: proxmox_hosts

  vars_files:
    - vars/proxmox_vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Install Proxmox Host dependencies
      ansible.builtin.apt:
        name:
          - libguestfs-tools
          - btop
          - tcpdump
          - jq
        state: present
      tags:
        - proxmox_host_setup

- name: Configure disk spin-down on brix
  hosts: brix
  become: true

  vars_files:
    - vars/brix_vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Enable backports repository
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: present
        filename: backports
      tags:
        - disk_spindown
        - backports

    - name: Install openSeaChest from backports
      ansible.builtin.apt:
        name:
          - openseachest
        state: present
        default_release: "{{ ansible_distribution_release }}-backports"
        update_cache: true
      tags:
        - disk_spindown
        - openseachest

    - name: Deploy disk spin-down systemd service
      ansible.builtin.template:
        src: templates/disk-spindown.service.j2
        dest: /etc/systemd/system/disk-spindown.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd daemon
      tags:
        - disk_spindown
        - systemd

    - name: Enable and start disk spin-down service
      ansible.builtin.systemd_service:
        name: disk-spindown.service
        enabled: true
        state: started
        daemon_reload: true
      tags:
        - disk_spindown
        - systemd

