---

- name: Proxmox Host Setup
  hosts: proxmox_hosts

  vars_files:
    - vars/proxmox_vars.yml

  vars:
    container_templates:
      - ubuntu-24.04-standard_24.04-2_amd64.tar.zst
      - debian-12-standard_12.12-1_amd64.tar.zst
      - debian-13-standard_13.1-1_amd64.tar.zst
  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Install Proxmox Host Ansible dependencies
      ansible.builtin.apt:
        name:
          - python3-proxmoxer
          - python3-requests
          - python3-paramiko
        state: present
      tags:
        - proxmox_host_setup

    - name: Download Container Templates
      community.general.proxmox_template:
        api_host: "{{ ansible_host | default(inventory_hostname) }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ vars[inventory_hostname.split('.')[0] + '_api_token_secret'] }}"
        node: "{{ inventory_hostname.split('.')[0] }}"
        storage: "{{ 'local-btrfs' if inventory_hostname.split('.')[0] == 'prox0' else 'local' }}"
        template: "{{ item }}"
        timeout: 600
      loop: "{{ container_templates }}"
      tags:
        - container_templates
        - proxmox_host_setup

