---
- name: Phase 1 - Download qcow2 cloud images
  ansible.builtin.import_playbook: playbooks/vm_template_setup.yml

- name: Phase 2 - Configure qcow2 cloud images
  ansible.builtin.import_playbook: playbooks/vm_template_customize.yml

- name: Phase 3 - Create VM templates
  ansible.builtin.import_playbook: playbooks/vm_template_create.yml
