---
- name: Download qcow2 cloud images
  hosts: proxmox_hosts
  gather_facts: false
  tags:
    - vm_templates

  vars:
    qcow2_storage_path: "/var/lib/vz/template/qemu"
    qcow2_images:
      - url: "https://cloud.debian.org/images/cloud/bookworm/20250923-2244/debian-12-generic-amd64-20250923-2244.qcow2"
        name: "debian-12-generic-amd64-20250923-2244.qcow2"
        vm_name: "debian-12"
        vmid: 1000
      - url: "https://cloud.debian.org/images/cloud/trixie/20250924-2245/debian-13-genericcloud-amd64-20250924-2245.qcow2"
        name: "debian-13-genericcloud-amd64-20250924-2245.qcow2"
        vm_name: "debian-13"
        vmid: 1001

  tasks:
    - name: Ensure qemu template directory exists
      ansible.builtin.file:
        path: "{{ qcow2_storage_path }}"
        state: directory
        mode: '0755'

    - name: Download qcow2 cloud images
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ qcow2_storage_path }}/{{ item.name }}"
        mode: '0644'
        timeout: 300
      loop: "{{ qcow2_images }}"

    - name: Verify qcow2 images were downloaded
      ansible.builtin.stat:
        path: "{{ qcow2_storage_path }}/{{ item.name }}"
      register: qcow2_stats
      loop: "{{ qcow2_images }}"

    - name: Display download results
      ansible.builtin.debug:
        msg: "{{ item.item.name }} successfully downloaded ({{ item.stat.size }} bytes)"
      loop: "{{ qcow2_stats.results }}"
      when: item.stat.exists

- name: Create VM templates
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - vm_templates

  vars_files:
    - vars/proxmox_vars.yml

  vars:
    qcow2_storage_path: "/var/lib/vz/template/qemu"
    template_configs:
      - hostname: brix.pcola.moorenix.com
        node: brix
        api_token_secret: "{{ lookup('env', 'BRIX_API_TOKEN_SECRET') | default(brix_api_token_secret, true) }}"
        storage: local-lvm
        templates:
          - vmid: 1000
            name: debian-12
            qcow2_file: "debian-12-generic-amd64-20250923-2244.qcow2"
          - vmid: 1001
            name: debian-13
            qcow2_file: "debian-13-genericcloud-amd64-20250924-2245.qcow2"
      - hostname: prox0.pcola.moorenix.com
        node: prox0
        api_token_secret: "{{ lookup('env', 'PROX0_API_TOKEN_SECRET') | default(prox0_api_token_secret, true) }}"
        storage: local-btrfs
        templates:
          - vmid: 1000
            name: debian-12
            qcow2_file: "debian-12-generic-amd64-20250923-2244.qcow2"
          - vmid: 1001
            name: debian-13
            qcow2_file: "debian-13-genericcloud-amd64-20250924-2245.qcow2"

  tasks:
    - name: Create VM for template
      community.proxmox.proxmox_kvm:
        api_host: "{{ item.0.hostname }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') | default(api_user, true) | default('root@pam') }}"
        api_password: "{{ lookup('env', 'PROXMOX_ROOT_PASSWORD') | default(root_password, true) }}"
        node: "{{ item.0.node }}"
        vmid: "{{ item.1.vmid }}"
        name: "{{ item.1.name }}"
        cpu: host
        sockets: 1
        cores: 2
        memory: 4096
        scsihw: virtio-scsi-pci
        net:
          net0: "virtio,bridge=vmbr0"
        ide:
          ide2: "{{ item.0.storage }}:cloudinit"
        boot: "order=scsi0"
        state: present
      loop: "{{ template_configs | subelements('templates') }}"
      loop_control:
        label: "{{ item.0.hostname }} - {{ item.1.name }}"

    - name: Import disk from qcow2 image
      community.proxmox.proxmox_disk:
        api_host: "{{ item.0.hostname }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') | default(api_user, true) | default('root@pam') }}"
        api_password: "{{ lookup('env', 'PROXMOX_ROOT_PASSWORD') | default(root_password, true) }}"
        vmid: "{{ item.1.vmid }}"
        disk: scsi0
        storage: "{{ item.0.storage }}"
        import_from: "{{ qcow2_storage_path }}/{{ item.1.qcow2_file }}"
        state: present
      loop: "{{ template_configs | subelements('templates') }}"
      loop_control:
        label: "{{ item.0.hostname }} - {{ item.1.name }}"

    - name: Convert VM to template
      community.proxmox.proxmox_kvm:
        api_host: "{{ item.0.hostname }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') | default(api_user, true) | default('root@pam') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') | default(api_token_id, true) | default('automation') }}"
        api_token_secret: "{{ item.0.api_token_secret }}"
        node: "{{ item.0.node }}"
        vmid: "{{ item.1.vmid }}"
        template: true
        update: true
      loop: "{{ template_configs | subelements('templates') }}"
      loop_control:
        label: "{{ item.0.hostname }} - {{ item.1.name }}"
