---

- name: Stop LXC Container
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host | default('brix.pcola.moorenix.com') }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid: "{{ lxc_vmid }}"
    state: stopped

- name: Start LXC Container
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host | default('brix.pcola.moorenix.com') }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid: "{{ lxc_vmid }}"
    state: started

- name: Restart LXC Container
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host | default('brix.pcola.moorenix.com') }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    vmid: "{{ lxc_vmid }}"
    state: restarted